version: "3.8"

services:
  cbb-api:
    build:
      context: .
      dockerfile: Dockerfile
      # Apple Silicon에서 AMD64로 빌드하려면 아래 주석 해제
      # platform: linux/amd64
    env_file:
      - .env.docker
    environment:
      # 덮어쓰기/보강 가능
      - CBB_SOUNDFONT_PATH=/app/assets/sf2/GeneralUserGS.sf2
    ports:
      - "8000:8000"
    volumes:
      # 산출물(미디/악보) 외부로 뽑기
      - ./recordings:/recordings
      # 필요하다면 tmp JSON도 호스트로 유지
      - ./LSTM/cli/data:/app/LSTM/cli/data
    restart: unless-stopped
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: /cbb/new-lstm/api
        awslogs-stream: cbb-api
        awslogs-create-group: "true"     # 드라이버가 그룹을 생성 시도(미지원 환경이면 2단계에서 미리 생성)


  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      # HTTPS 붙일 계획이면 나중에 "443:443"도 열 예정
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - cbb-api
    restart: unless-stopped
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: /cbb/new-lstm/nginx
        awslogs-stream: nginx
        awslogs-create-group: "true"